version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: foundation-rails
    versions:
    - "> 5.5.3.2"
  - dependency-name: pg
    versions:
    - ">= 1.2.a, < 1.3"
  - dependency-name: stripe
    versions:
    - "> 4.18.1"
