# Find out more about the rubocop cops  https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

AllCops:
  Exclude:
    - db/**/*
    - spec/**/*

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/Date:
  Enabled: true
