development: &default
  adapter: postgresql
  encoding: unicode
  database: planner_development
  pool: 5
  username: <%= ENV['DB_USER'] || ''  %>
  password: <%= ENV['POSTGRES_PASSWORD'] || '' %>
  host: <%= (ENV['DB_HOST'] || 'localhost').to_json %>

test:
  <<: *default
  database: planner_test
  pool: 5
